---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: hardeningcentos8
    box: centos/8
    box_version: 1905.1
    memory: 4096
    cpus: 4
    provision: true
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 22222, host: 22221"
  - name: hardeningdebian10
    box: debian/buster64
    box_version: 10.3.0
    memory: 4096
    cpus: 4
    provision: true
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 22222, host: 22222"
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
verifier:
  name: ansible
lint: |
  set -e
  yamllint -c .yamllint .
  flake8
  ansible-lint
